### ISSUE TITLE
adding users explanation

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE#86]
Hi,

The document page: http://eudat-b2safe.github.io/B2HANDLE/givingpermissiontousers.html#givingpermissiontousers shows how to add users.

The following works:

`0.NA/846`:

|  index    | key    | value    |
| ---------- | -------- | ---------- |
| 100       | HS_ADMIN |  0.NA/846: index:200 |
| 200       | HS_VLIST   | 0.NA/846: index 300: 846/ADMIN: index 200 |
| 300       | HS_PUBKEY | pub key generated by bla |

`846/ADMIN:`

|  index    | key    | value    |
| ---------- | -------- | ---------- |
| 100       | HS_ADMIN |  0.NA/846: index:200 |
| 200       | HS_VLIST   | 846/ADMIN: index 300: 846/USER1: index 200 |
| 300       | HS_PUBKEY | pub key generated by bla |

`846/USER1:`

|  index    | key    | value    |
| ----------- | -------- | ---------- |
| 100        | HS_ADMIN | 0.NA/846: index:200 |
| 200        | HS_VLIST | 846/USER: index 300:846/USER1: index 310: |
| 300        | HS_PUBKEY | pub key generated by bla |
| 310        | HS_PUBKEY | pub key generated by customer |

Than USER1 is able to create new handles with the ADMIN key `0.NA/846: index 200`

If I follow the setup on the page it does not work as expected. It is difficult to setup `846/ADMIN` and `846/USER1` and NOT possible to create handles.

How to set it up so nobody is able to modify `846/ADMIN` or `846/USER1` except  `846/ADMIN` or `846/USER1`?

**Comment by merretbuurman** [comment]
Hi!
There was a detail missing on the page, so I will update the docs for the next release. Thanks for pointing that out. The missing part is that in the third method on the docs page you refer to, the HS_VLIST has to contain *both* HS_VLISTs from the foo/admin record, to make sure the admin has write permissions. See attached screenshot.

I'll add a recommendation how to solve your problem in another comment.
![docs_update](https://cloud.githubusercontent.com/assets/13016367/15856845/7a57020a-2cb8-11e6-8cc7-94d976424dae.png)

**Comment by merretbuurman** [comment]
> How to set it up so nobody is able to modify |846/ADMIN| or |846/USER1|
> except |846/ADMIN| or |846/USER1|?

So far, more people are able to modify them, because their HS_ADMIN points to 200:0.NA/846, which points (indirectly) to the pubkeys at 300:0.NA/846, 300:846/ADMIN, 300:846/USER1 and 310:846/USER1, so all of these can modify all handles that have 200:0.NA/846 in the HS_ADMIN.

If you want only USER1 (both pubkeys) to modify 846/USER1, do this: In the HS_ADMIN of 846/USER1, point to 200:846/USER1, instead of 200:0.NA/846.

If you want only ADMIN to modify 846/ADMIN, do this: In the HS_ADMIN of 846/ADMIN, point to his pubkey in 300:846/ADMIN.

I'd recommend separating the HS_VLIST 200:846/ADMIN into two HS_VLISTs, say 201:846/ADMIN and 202:846/ADMIN, as it is described in the third method in the page you refer to. (Then, those two lists have to be referred to in 200:846/ADMIN or in 200:0.NA/846 - this was the missing part on the page).

Does this help?

**Comment by cookie33** [comment]
Hi,

This will fix my problems. I will wait for the documentation to implement it.

For Now I did it so each user (846/ADMIN and 846/USER1) is able to modify everything including the admin and user handles. But this is a test environment. There it is allowed :)

In real live we want something different.

**Comment by merretbuurman** [comment]
The updated docs are included in releas 1.0.3.
